apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ku3qk8mvj-python 
  janus-idp.io/tekton: ku3qk8mvj-python
  backstage.io/kubernetes-id: ku3qk8mvj-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ku3qk8mvj-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml