apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ku3qk8mvj-python
  janus-idp.io/tekton: ku3qk8mvj-python
  backstage.io/kubernetes-id: ku3qk8mvj-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ku3qk8mvj-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
